### ISSUE TITLE
Config not shown in UI

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/sdl-visualization#108]
after registering and uploading the SDLB config in the frontend I get: 

```
Error: fetchAPI for REST does not support getting config without version specified, but parameter version was undefined
    at _Ct.getConfig (index-CQ7FQ8-i.js:348:6938)
    at Object.queryFn (index-CQ7FQ8-i.js:441:20761)
    at Object.p [as fn] (index-CQ7FQ8-i.js:250:122738)
    at f (index-CQ7FQ8-i.js:250:117457)
    at new Txe (index-CQ7FQ8-i.js:250:118076)
    at t.fetch (index-CQ7FQ8-i.js:250:123197)
    at r.executeFetch (index-CQ7FQ8-i.js:250:141380)
    at r.onSubscribe (index-CQ7FQ8-i.js:250:138913)
    at t.subscribe (index-CQ7FQ8-i.js:250:111071)
    at index-CQ7FQ8-i.js:250:151338
```
I use the snapshot version 2.7.2.896-SNAPSHOT
Even after running and uploading a state. The state is visible, but the config cannot be seen. 
I tried multiple Browsers and re-logins. I always get the loading sign:

![image](https://github.com/user-attachments/assets/06b06119-ef75-467a-b38a-8cdc62d39fc8)

**Comment by mand35** [comment]
I needed to realize that I called the INT frontend. The PROD frontend works as expected
