### ISSUE TITLE
Fix sync between showing Action ins Graph and the corresponding Button

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/sdl-visualization#73]
Current Behaviour
In Configuration Lineage Graph view, when 
1) showing Actions is enabled and disabled again,
2) DataObject is changed
then Actions show again, but Button is still disabled

Expected Behaviour
After 1) & 2), Action Button stays disabled and Actions are not show in Graph visualization

**Comment by HX-Tfd** [comment]
Is this problem related to the existence of the index files? When clicking on the dataObject node that has no schema, the HoconParser throws an error:
```
 Error: Could not read /schema/btl-departures-arrivals-airports.schema.index because it does not exist (rerouted to index.html)
    at HoconParser.ts:137:68
useFetchData.tsx:62 Error: Could not read /schema/btl-departures-arrivals-airports.stats.index because it does not exist (rerouted to index.html)
    at HoconParser.ts:137:68
```
 I see that @zzeekk added some schemas for testing, does it work now? On my branch, this doesn't work even with the schemas added. I suspect that it is due to re-computation of the layout, but I still have to debug it.

**Comment by HX-Tfd** [comment]
done with #82
